defaults: &defaults
  roles:
    - admin
    - order_admin
    - content_admin
    - order_submitter
    - user
    - guest
  default_role: user

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
