# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fc54fb083d7648aadf4693cb3eeec6feeb692f7c2f5ec3bbbd03f186a4086fa5bcf5fe1c8117283066c8923ec17294cf6e83878136de08b8f4e32d957f5b55f

test:
  secret_key_base: 916ed25a3e6d05c33400137ad6f8e09c99419bd65b4168e1df4984625910b41208cb363e10950e58ccc40de6f169c95653e1ce69db360464d44501290109dd3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
